import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { TremorSession } from '../types/session';
import { pdfColors } from '../theme/tokens';

function buildReportHTML(sessions: TremorSession[], patientName: string): string {
  const sorted = [...sessions].sort((a, b) => a.timestamp - b.timestamp);
  const scores = sorted.map((s) => s.score);
  const avg = Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
  const trend = scores[scores.length - 1] - scores[0];
  const trendLabel = trend > 5 ? 'Improving' : trend < -5 ? 'Declining' : 'Stable';

  const dateRange =
    sorted.length > 0
      ? `${new Date(sorted[0].timestamp).toLocaleDateString()} – ${new Date(
          sorted[sorted.length - 1].timestamp
        ).toLocaleDateString()}`
      : 'No sessions';

  const rows = sorted
    .map(
      (s) => `
    <tr>
      <td>${new Date(s.timestamp).toLocaleDateString()}</td>
      <td>${s.score}</td>
      <td>${s.dominantFreqHz} Hz</td>
      <td>${s.hand}</td>
    </tr>`
    )
    .join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; padding: 32px; color: ${pdfColors.text}; }
    h1 { color: ${pdfColors.primaryDark}; }
    h2 { color: ${pdfColors.primary}; margin-top: 32px; }
    .summary { background: ${pdfColors.primaryMuted}; border-radius: 8px; padding: 16px; margin: 16px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th { background: ${pdfColors.primary}; color: white; padding: 8px; text-align: left; }
    td { padding: 8px; border-bottom: 1px solid ${pdfColors.border}; }
    .footer { margin-top: 48px; font-size: 12px; color: ${pdfColors.textHint}; border-top: 1px solid ${pdfColors.border}; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>TremorLog Report</h1>
  <p><strong>Patient:</strong> ${patientName}</p>
  <p><strong>Period:</strong> ${dateRange}</p>
  <p><strong>Sessions:</strong> ${sessions.length}</p>

  <h2>Summary</h2>
  <div class="summary">
    <p><strong>Average Stability Score:</strong> ${avg}/100</p>
    <p><strong>Trend:</strong> ${trendLabel} (${trend > 0 ? '+' : ''}${trend} pts)</p>
  </div>

  <h2>Sessions</h2>
  <table>
    <thead>
      <tr><th>Date</th><th>Score</th><th>Frequency</th><th>Hand</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    This is a symptom log, not a medical diagnosis. Share with your neurologist.
    Generated by TremorLog.
  </div>
</body>
</html>`;
}

export async function generateReport(
  sessions: TremorSession[],
  patientName: string = 'Anonymous'
): Promise<string> {
  const html = buildReportHTML(sessions, patientName);
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
}

export async function shareReport(filePath: string): Promise<void> {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(filePath, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share tremor report with your doctor',
    });
  }
}
